AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Policy DAG Inference

Globals:
  Function:
    Timeout: 5
    MemorySize: 256
    Environment:
      Variables:
        POLICY_CACHE_MAX_ITEMS: "1024"
        POLICY_MAX_STEPS: "10000"
        POLICY_OBS_BUFFER: "4096"

Resources:
  InferFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2023
      Architectures:
        - arm64
      Handler: bootstrap
      CodeUri: build/
      Events:
        Infer:
          Type: HttpApi
          Properties:
            Path: /infer
            Method: POST
